In [5]:
import pandas as pd
import numpy as np

# 1) LOAD DATA
path = r"C:\SALMAAAAAA\Salma As Student\Machine Learning\ta-ml-jabar-2024\data\master\Master Data - fitur & label.xlsx"
df = pd.read_excel(path)

print(df.shape)
display(df.head())

# 2) PILIH FEATURE & TARGET
target = "kelas_layanan"

feature_cols = [
    "kepadatan_penduduk",
    "rasio_apotek", "rasio_puskesmas_total", "rasio_klinik", "rasio_rsu_total",
    "dens_apotek",  "dens_puskesmas_total",  "dens_klinik",  "dens_rsu_total"
]

# cek kolom yang kepakai ada semua
missing = [c for c in [target, "kab_kota"] + feature_cols if c not in df.columns]
if missing:
    raise ValueError(f"Kolom ini tidak ada di dataframe: {missing}")

X = df[feature_cols]
y = df[target]

# 3) MODEL + EVALUASI (CV)
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    class_weight="balanced"
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_pred = cross_val_predict(model, X, y, cv=cv)

print("\n=== Classification Report (CV) ===")
print(classification_report(y, y_pred))

print("\n=== Confusion Matrix (CV) ===")
print(confusion_matrix(y, y_pred, labels=["Rendah", "Sedang", "Tinggi"]))


# 4) FEATURE IMPORTANCE
model.fit(X, y)
imp = pd.Series(model.feature_importances_, index=feature_cols).sort_values(ascending=False)

print("\n=== Feature Importance ===")
display(imp)

# simpan importance ke file (opsional)
imp.to_csv(r"C:\SALMAAAAAA\Salma As Student\Machine Learning\ta-ml-jabar-2024\outputs\feature_importance.csv")


# 5) TOP/BOTTOM RASIO (5 TERENDAH & 5 TERTINGGI)
def top_bottom(df, daerah_col, metric_col, n=5):
    tmp = df[[daerah_col, metric_col]].sort_values(metric_col)
    bottom = tmp.head(n).reset_index(drop=True)
    top = tmp.tail(n).sort_values(metric_col, ascending=False).reset_index(drop=True)
    return bottom, top

daerah_col = "kab_kota"

rasio_metrics = [
    "rasio_apotek",
    "rasio_puskesmas_total",
    "rasio_klinik",
    "rasio_rsu_total"
]

for m in rasio_metrics:
    bottom, top = top_bottom(df, daerah_col, m, n=5)
    print(f"\n===== {m}: 5 TERENDAH =====")
    display(bottom)
    print(f"===== {m}: 5 TERTINGGI =====")
    display(top)

# ranking berdasarkan skor gabungan :
print("\n===== Skor Gabungan (skor_layanan): 5 TERENDAH =====")
display(df[[daerah_col, "skor_layanan", "kelas_layanan"]].sort_values("skor_layanan").head(5))

print("\n===== Skor Gabungan (skor_layanan): 5 TERTINGGI =====")
display(df[[daerah_col, "skor_layanan", "kelas_layanan"]].sort_values("skor_layanan", ascending=False).head(5))

# Top 7 fitur paling berpengaruh
import pandas as pd

imp = pd.read_csv(
    r"C:\SALMAAAAAA\Salma As Student\Machine Learning\ta-ml-jabar-2024\outputs\feature_importance.csv",
    header=None, index_col=0
).squeeze("columns")

imp = imp.sort_values(ascending=False)
display(imp.head(7))

import pandas as pd

rank_path = r"C:\SALMAAAAAA\Salma As Student\Machine Learning\ta-ml-jabar-2024\outputs\tables\ranking_top_bottom_2024.xlsx"
xls = pd.ExcelFile(rank_path)
print(xls.sheet_names)





(27, 19)


,kode_kab_kota,kab_kota,luas_km2,kepadatan_penduduk,apotek,puskesmas_total,klinik,rsu_total,penduduk_2024,rasio_apotek,dens_apotek,rasio_puskesmas_total,dens_puskesmas_total,rasio_klinik,dens_klinik,rasio_rsu_total,dens_rsu_total,skor_layanan,kelas_layanan
0,3201,KABUPATEN BOGOR,2991.78,1899,466,258,45,27,5681390.22,0.820222,0.155760,0.454114,0.086236,0.079206,0.015041,0.047524,0.009025,-0.771693,Rendah
1,3202,KABUPATEN SUKABUMI,4164.15,679,206,282,9,9,2827457.85,0.728570,0.049470,0.997362,0.067721,0.031831,0.002161,0.031831,0.002161,-0.616339,Rendah
2,3203,KABUPATEN CIANJUR,3631.92,712,219,157,10,7,2585927.04,0.846892,0.060299,0.607132,0.043228,0.038671,0.002753,0.027070,0.001927,-0.843022,Rendah
3,3204,KABUPATEN BANDUNG,1740.84,2156,418,100,14,17,3753251.04,1.113701,0.240114,0.266436,0.057444,0.037301,0.008042,0.045294,0.009765,-0.910243,Rendah
4,3205,KABUPATEN GARUT,3101.24,876,325,276,10,9,2716686.24,1.196310,0.104797,1.015944,0.088997,0.036810,0.003225,0.033129,0.002902,-0.413293,Rendah



=== Classification Report (CV) ===
              precision    recall  f1-score   support

      Rendah       1.00      0.89      0.94         9
      Sedang       0.70      0.78      0.74         9
      Tinggi       0.78      0.78      0.78         9

    accuracy                           0.81        27
   macro avg       0.83      0.81      0.82        27
weighted avg       0.83      0.81      0.82        27


=== Confusion Matrix (CV) ===
[[8 1 0]
 [0 7 2]
 [0 2 7]]

=== Feature Importance ===


rasio_apotek             0.305329
rasio_rsu_total          0.185986
rasio_klinik             0.120371
dens_puskesmas_total     0.083384
rasio_puskesmas_total    0.064789
dens_apotek              0.062938
dens_rsu_total           0.062641
kepadatan_penduduk       0.061575
dens_klinik              0.052987
dtype: float64


===== rasio_apotek: 5 TERENDAH =====


,kab_kota,rasio_apotek
0,KABUPATEN SUKABUMI,0.728570
1,KABUPATEN BOGOR,0.820222
2,KABUPATEN CIANJUR,0.846892
3,KABUPATEN INDRAMAYU,0.961274
4,KABUPATEN TASIKMALAYA,1.015011


===== rasio_apotek: 5 TERTINGGI =====


,kab_kota,rasio_apotek
0,KOTA CIREBON,3.305657
1,KOTA TASIKMALAYA,3.197190
2,KOTA BANDUNG,2.760890
3,KOTA BEKASI,2.586951
4,KOTA BANJAR,2.431501



===== rasio_puskesmas_total: 5 TERENDAH =====


,kab_kota,rasio_puskesmas_total
0,KOTA BEKASI,0.181540
1,KOTA CIMAHI,0.250548
2,KABUPATEN BANDUNG,0.266436
3,KOTA DEPOK,0.295800
4,KOTA BANDUNG,0.316434


===== rasio_puskesmas_total: 5 TERTINGGI =====


,kab_kota,rasio_puskesmas_total
0,KABUPATEN CIAMIS,1.469191
1,KOTA SUKABUMI,1.312354
2,KOTA BANJAR,1.287265
3,KABUPATEN KUNINGAN,1.251676
4,KABUPATEN PANGANDARAN,1.105101



===== rasio_klinik: 5 TERENDAH =====


,kab_kota,rasio_klinik
0,KABUPATEN TASIKMALAYA,0.000000
1,KOTA CIREBON,0.000000
2,KOTA BANDUNG,0.031643
3,KABUPATEN SUKABUMI,0.031831
4,KABUPATEN GARUT,0.036810


===== rasio_klinik: 5 TERTINGGI =====


,kab_kota,rasio_klinik
0,KOTA BANJAR,0.381412
1,KOTA DEPOK,0.300422
2,KOTA BOGOR,0.287464
3,KOTA BEKASI,0.268529
4,KABUPATEN BEKASI,0.204648



===== rasio_rsu_total: 5 TERENDAH =====


,kab_kota,rasio_rsu_total
0,KABUPATEN TASIKMALAYA,0.005205
1,KABUPATEN PANGANDARAN,0.023023
2,KABUPATEN CIANJUR,0.027070
3,KABUPATEN SUKABUMI,0.031831
4,KABUPATEN BANDUNG BARAT,0.031846


===== rasio_rsu_total: 5 TERTINGGI =====


,kab_kota,rasio_rsu_total
0,KOTA CIREBON,0.260973
1,KOTA BANJAR,0.190706
2,KOTA BEKASI,0.173976
3,KOTA BOGOR,0.166915
4,KOTA SUKABUMI,0.164044



===== Skor Gabungan (skor_layanan): 5 TERENDAH =====


,kab_kota,skor_layanan,kelas_layanan
3,KABUPATEN BANDUNG,-0.910243,Rendah
2,KABUPATEN CIANJUR,-0.843022,Rendah
16,KABUPATEN BANDUNG BARAT,-0.822972,Rendah
0,KABUPATEN BOGOR,-0.771693,Rendah
5,KABUPATEN TASIKMALAYA,-0.669555,Rendah



===== Skor Gabungan (skor_layanan): 5 TERTINGGI =====


,kab_kota,skor_layanan,kelas_layanan
26,KOTA BANJAR,1.749353,Tinggi
21,KOTA CIREBON,1.138263,Tinggi
19,KOTA SUKABUMI,1.028243,Tinggi
25,KOTA TASIKMALAYA,0.836751,Tinggi
22,KOTA BEKASI,0.685918,Tinggi


0
rasio_apotek             0.305329
rasio_rsu_total          0.185986
rasio_klinik             0.120371
dens_puskesmas_total     0.083384
rasio_puskesmas_total    0.064789
dens_apotek              0.062938
dens_rsu_total           0.062641
Name: 1, dtype: float64

['rasio_apotek_bottom', 'rasio_apotek_top', 'rasio_puskesmas_total_bottom', 'rasio_puskesmas_total_top', 'rasio_klinik_bottom', 'rasio_klinik_top', 'rasio_rsu_total_bottom', 'rasio_rsu_total_top']
